//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funeral.Web.niws_partner {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ServiceInfoList", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS", ItemName="ServiceInfo")]
    [System.SerializableAttribute()]
    public class ServiceInfoList : System.Collections.Generic.List<Funeral.DAL.niws_partner.ServiceInfo> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ServiceInfoResponseList", Namespace="http://schemas.datacontract.org/2004/07/NC.DG.TMS.C.WCF.NIWS", ItemName="ServiceInfoResponse")]
    [System.SerializableAttribute()]
    public class ServiceInfoResponseList : System.Collections.Generic.List<Funeral.DAL.niws_partner.ServiceInfoResponse> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="niws_partner.INIWS_Partner")]
    public interface INIWS_Partner {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/BatchFileUpload", ReplyAction="http://tempuri.org/INIWS_Partner/BatchFileUploadResponse")]
        string BatchFileUpload(string serviceKey, string file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/BatchFileUpload", ReplyAction="http://tempuri.org/INIWS_Partner/BatchFileUploadResponse")]
        System.Threading.Tasks.Task<string> BatchFileUploadAsync(string serviceKey, string file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/RequestFileUploadReport", ReplyAction="http://tempuri.org/INIWS_Partner/RequestFileUploadReportResponse")]
        string RequestFileUploadReport(string serviceKey, string fileToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/RequestFileUploadReport", ReplyAction="http://tempuri.org/INIWS_Partner/RequestFileUploadReportResponse")]
        System.Threading.Tasks.Task<string> RequestFileUploadReportAsync(string serviceKey, string fileToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/ValidateServiceKey", ReplyAction="http://tempuri.org/INIWS_Partner/ValidateServiceKeyResponse")]
        Funeral.DAL.niws_partner.ValidateServiceKeyResponse ValidateServiceKey(Funeral.DAL.niws_partner.ValidateServiceKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/ValidateServiceKey", ReplyAction="http://tempuri.org/INIWS_Partner/ValidateServiceKeyResponse")]
        System.Threading.Tasks.Task<Funeral.DAL.niws_partner.ValidateServiceKeyResponse> ValidateServiceKeyAsync(Funeral.DAL.niws_partner.ValidateServiceKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/AccountSupportMessage", ReplyAction="http://tempuri.org/INIWS_Partner/AccountSupportMessageResponse")]
        string AccountSupportMessage(string partnerServiceKey, string serviceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/AccountSupportMessage", ReplyAction="http://tempuri.org/INIWS_Partner/AccountSupportMessageResponse")]
        System.Threading.Tasks.Task<string> AccountSupportMessageAsync(string partnerServiceKey, string serviceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/RequestAccountStatus", ReplyAction="http://tempuri.org/INIWS_Partner/RequestAccountStatusResponse")]
        string RequestAccountStatus(string partnerServiceKey, string pastelAccountNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/RequestAccountStatus", ReplyAction="http://tempuri.org/INIWS_Partner/RequestAccountStatusResponse")]
        System.Threading.Tasks.Task<string> RequestAccountStatusAsync(string partnerServiceKey, string pastelAccountNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/RetrieveAccountStatus", ReplyAction="http://tempuri.org/INIWS_Partner/RetrieveAccountStatusResponse")]
        string RetrieveAccountStatus(string ServiceKey, string FileToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/RetrieveAccountStatus", ReplyAction="http://tempuri.org/INIWS_Partner/RetrieveAccountStatusResponse")]
        System.Threading.Tasks.Task<string> RetrieveAccountStatusAsync(string ServiceKey, string FileToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/RetrievePNSHandle", ReplyAction="http://tempuri.org/INIWS_Partner/RetrievePNSHandleResponse")]
        string RetrievePNSHandle(string ServiceKey, int SystemUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/RetrievePNSHandle", ReplyAction="http://tempuri.org/INIWS_Partner/RetrievePNSHandleResponse")]
        System.Threading.Tasks.Task<string> RetrievePNSHandleAsync(string ServiceKey, int SystemUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/PartnerAuth", ReplyAction="http://tempuri.org/INIWS_Partner/PartnerAuthResponse")]
        string PartnerAuth(string ServiceKey, int SystemUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/PartnerAuth", ReplyAction="http://tempuri.org/INIWS_Partner/PartnerAuthResponse")]
        System.Threading.Tasks.Task<string> PartnerAuthAsync(string ServiceKey, int SystemUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/CreateOrUpdatePNSHandle", ReplyAction="http://tempuri.org/INIWS_Partner/CreateOrUpdatePNSHandleResponse")]
        string CreateOrUpdatePNSHandle(string ServiceKey, int SystemUserID, string PNSHandle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/CreateOrUpdatePNSHandle", ReplyAction="http://tempuri.org/INIWS_Partner/CreateOrUpdatePNSHandleResponse")]
        System.Threading.Tasks.Task<string> CreateOrUpdatePNSHandleAsync(string ServiceKey, int SystemUserID, string PNSHandle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/DeletePNSHandle", ReplyAction="http://tempuri.org/INIWS_Partner/DeletePNSHandleResponse")]
        string DeletePNSHandle(string ServiceKey, int SystemUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/DeletePNSHandle", ReplyAction="http://tempuri.org/INIWS_Partner/DeletePNSHandleResponse")]
        System.Threading.Tasks.Task<string> DeletePNSHandleAsync(string ServiceKey, int SystemUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/ValidateComplianceStatus", ReplyAction="http://tempuri.org/INIWS_Partner/ValidateComplianceStatusResponse")]
        Funeral.DAL.niws_partner.ValidateComplianceResponse ValidateComplianceStatus(Funeral.DAL.niws_partner.ValidateComplianceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Partner/ValidateComplianceStatus", ReplyAction="http://tempuri.org/INIWS_Partner/ValidateComplianceStatusResponse")]
        System.Threading.Tasks.Task<Funeral.DAL.niws_partner.ValidateComplianceResponse> ValidateComplianceStatusAsync(Funeral.DAL.niws_partner.ValidateComplianceRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INIWS_PartnerChannel : Funeral.Web.niws_partner.INIWS_Partner, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NIWS_PartnerClient : System.ServiceModel.ClientBase<Funeral.Web.niws_partner.INIWS_Partner>, Funeral.Web.niws_partner.INIWS_Partner {
        
        public NIWS_PartnerClient() {
        }
        
        public NIWS_PartnerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NIWS_PartnerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NIWS_PartnerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NIWS_PartnerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string BatchFileUpload(string serviceKey, string file) {
            return base.Channel.BatchFileUpload(serviceKey, file);
        }
        
        public System.Threading.Tasks.Task<string> BatchFileUploadAsync(string serviceKey, string file) {
            return base.Channel.BatchFileUploadAsync(serviceKey, file);
        }
        
        public string RequestFileUploadReport(string serviceKey, string fileToken) {
            return base.Channel.RequestFileUploadReport(serviceKey, fileToken);
        }
        
        public System.Threading.Tasks.Task<string> RequestFileUploadReportAsync(string serviceKey, string fileToken) {
            return base.Channel.RequestFileUploadReportAsync(serviceKey, fileToken);
        }
        
        public Funeral.DAL.niws_partner.ValidateServiceKeyResponse ValidateServiceKey(Funeral.DAL.niws_partner.ValidateServiceKeyRequest request) {
            return base.Channel.ValidateServiceKey(request);
        }
        
        public System.Threading.Tasks.Task<Funeral.DAL.niws_partner.ValidateServiceKeyResponse> ValidateServiceKeyAsync(Funeral.DAL.niws_partner.ValidateServiceKeyRequest request) {
            return base.Channel.ValidateServiceKeyAsync(request);
        }
        
        public string AccountSupportMessage(string partnerServiceKey, string serviceKey) {
            return base.Channel.AccountSupportMessage(partnerServiceKey, serviceKey);
        }
        
        public System.Threading.Tasks.Task<string> AccountSupportMessageAsync(string partnerServiceKey, string serviceKey) {
            return base.Channel.AccountSupportMessageAsync(partnerServiceKey, serviceKey);
        }
        
        public string RequestAccountStatus(string partnerServiceKey, string pastelAccountNo) {
            return base.Channel.RequestAccountStatus(partnerServiceKey, pastelAccountNo);
        }
        
        public System.Threading.Tasks.Task<string> RequestAccountStatusAsync(string partnerServiceKey, string pastelAccountNo) {
            return base.Channel.RequestAccountStatusAsync(partnerServiceKey, pastelAccountNo);
        }
        
        public string RetrieveAccountStatus(string ServiceKey, string FileToken) {
            return base.Channel.RetrieveAccountStatus(ServiceKey, FileToken);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveAccountStatusAsync(string ServiceKey, string FileToken) {
            return base.Channel.RetrieveAccountStatusAsync(ServiceKey, FileToken);
        }
        
        public string RetrievePNSHandle(string ServiceKey, int SystemUserID) {
            return base.Channel.RetrievePNSHandle(ServiceKey, SystemUserID);
        }
        
        public System.Threading.Tasks.Task<string> RetrievePNSHandleAsync(string ServiceKey, int SystemUserID) {
            return base.Channel.RetrievePNSHandleAsync(ServiceKey, SystemUserID);
        }
        
        public string PartnerAuth(string ServiceKey, int SystemUserID) {
            return base.Channel.PartnerAuth(ServiceKey, SystemUserID);
        }
        
        public System.Threading.Tasks.Task<string> PartnerAuthAsync(string ServiceKey, int SystemUserID) {
            return base.Channel.PartnerAuthAsync(ServiceKey, SystemUserID);
        }
        
        public string CreateOrUpdatePNSHandle(string ServiceKey, int SystemUserID, string PNSHandle) {
            return base.Channel.CreateOrUpdatePNSHandle(ServiceKey, SystemUserID, PNSHandle);
        }
        
        public System.Threading.Tasks.Task<string> CreateOrUpdatePNSHandleAsync(string ServiceKey, int SystemUserID, string PNSHandle) {
            return base.Channel.CreateOrUpdatePNSHandleAsync(ServiceKey, SystemUserID, PNSHandle);
        }
        
        public string DeletePNSHandle(string ServiceKey, int SystemUserID) {
            return base.Channel.DeletePNSHandle(ServiceKey, SystemUserID);
        }
        
        public System.Threading.Tasks.Task<string> DeletePNSHandleAsync(string ServiceKey, int SystemUserID) {
            return base.Channel.DeletePNSHandleAsync(ServiceKey, SystemUserID);
        }
        
        public Funeral.DAL.niws_partner.ValidateComplianceResponse ValidateComplianceStatus(Funeral.DAL.niws_partner.ValidateComplianceRequest request) {
            return base.Channel.ValidateComplianceStatus(request);
        }
        
        public System.Threading.Tasks.Task<Funeral.DAL.niws_partner.ValidateComplianceResponse> ValidateComplianceStatusAsync(Funeral.DAL.niws_partner.ValidateComplianceRequest request) {
            return base.Channel.ValidateComplianceStatusAsync(request);
        }
    }
}
