//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funeral.Web.niws_validation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="niws_validation.INIWS_Validation")]
    public interface INIWS_Validation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Validation/ValidateBankAccount", ReplyAction="http://tempuri.org/INIWS_Validation/ValidateBankAccountResponse")]
        string ValidateBankAccount(string ServiceKey, string AccountNumber, string BranchCode, string AccountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Validation/ValidateBankAccount", ReplyAction="http://tempuri.org/INIWS_Validation/ValidateBankAccountResponse")]
        System.Threading.Tasks.Task<string> ValidateBankAccountAsync(string ServiceKey, string AccountNumber, string BranchCode, string AccountType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Validation/ValidateBranchCode", ReplyAction="http://tempuri.org/INIWS_Validation/ValidateBranchCodeResponse")]
        string ValidateBranchCode(string ServiceKey, string BranchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Validation/ValidateBranchCode", ReplyAction="http://tempuri.org/INIWS_Validation/ValidateBranchCodeResponse")]
        System.Threading.Tasks.Task<string> ValidateBranchCodeAsync(string ServiceKey, string BranchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Validation/GetBankList", ReplyAction="http://tempuri.org/INIWS_Validation/GetBankListResponse")]
        string GetBankList(string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Validation/GetBankList", ReplyAction="http://tempuri.org/INIWS_Validation/GetBankListResponse")]
        System.Threading.Tasks.Task<string> GetBankListAsync(string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Validation/GetBankListWithDefaultBranchCode", ReplyAction="http://tempuri.org/INIWS_Validation/GetBankListWithDefaultBranchCodeResponse")]
        string GetBankListWithDefaultBranchCode(string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Validation/GetBankListWithDefaultBranchCode", ReplyAction="http://tempuri.org/INIWS_Validation/GetBankListWithDefaultBranchCodeResponse")]
        System.Threading.Tasks.Task<string> GetBankListWithDefaultBranchCodeAsync(string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Validation/GetBranchList", ReplyAction="http://tempuri.org/INIWS_Validation/GetBranchListResponse")]
        string GetBranchList(string ServiceKey, string BankName, string BranchName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Validation/GetBranchList", ReplyAction="http://tempuri.org/INIWS_Validation/GetBranchListResponse")]
        System.Threading.Tasks.Task<string> GetBranchListAsync(string ServiceKey, string BankName, string BranchName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Validation/ValidateId", ReplyAction="http://tempuri.org/INIWS_Validation/ValidateIdResponse")]
        string ValidateId(string ServiceKey, string IdNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Validation/ValidateId", ReplyAction="http://tempuri.org/INIWS_Validation/ValidateIdResponse")]
        System.Threading.Tasks.Task<string> ValidateIdAsync(string ServiceKey, string IdNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Validation/GetBranchListBySuburb", ReplyAction="http://tempuri.org/INIWS_Validation/GetBranchListBySuburbResponse")]
        string GetBranchListBySuburb(string ServiceKey, string BankName, string SuburbName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INIWS_Validation/GetBranchListBySuburb", ReplyAction="http://tempuri.org/INIWS_Validation/GetBranchListBySuburbResponse")]
        System.Threading.Tasks.Task<string> GetBranchListBySuburbAsync(string ServiceKey, string BankName, string SuburbName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INIWS_ValidationChannel : Funeral.Web.niws_validation.INIWS_Validation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NIWS_ValidationClient : System.ServiceModel.ClientBase<Funeral.Web.niws_validation.INIWS_Validation>, Funeral.Web.niws_validation.INIWS_Validation {
        
        public NIWS_ValidationClient() {
        }
        
        public NIWS_ValidationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NIWS_ValidationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NIWS_ValidationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NIWS_ValidationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ValidateBankAccount(string ServiceKey, string AccountNumber, string BranchCode, string AccountType) {
            return base.Channel.ValidateBankAccount(ServiceKey, AccountNumber, BranchCode, AccountType);
        }
        
        public System.Threading.Tasks.Task<string> ValidateBankAccountAsync(string ServiceKey, string AccountNumber, string BranchCode, string AccountType) {
            return base.Channel.ValidateBankAccountAsync(ServiceKey, AccountNumber, BranchCode, AccountType);
        }
        
        public string ValidateBranchCode(string ServiceKey, string BranchCode) {
            return base.Channel.ValidateBranchCode(ServiceKey, BranchCode);
        }
        
        public System.Threading.Tasks.Task<string> ValidateBranchCodeAsync(string ServiceKey, string BranchCode) {
            return base.Channel.ValidateBranchCodeAsync(ServiceKey, BranchCode);
        }
        
        public string GetBankList(string ServiceKey) {
            return base.Channel.GetBankList(ServiceKey);
        }
        
        public System.Threading.Tasks.Task<string> GetBankListAsync(string ServiceKey) {
            return base.Channel.GetBankListAsync(ServiceKey);
        }
        
        public string GetBankListWithDefaultBranchCode(string ServiceKey) {
            return base.Channel.GetBankListWithDefaultBranchCode(ServiceKey);
        }
        
        public System.Threading.Tasks.Task<string> GetBankListWithDefaultBranchCodeAsync(string ServiceKey) {
            return base.Channel.GetBankListWithDefaultBranchCodeAsync(ServiceKey);
        }
        
        public string GetBranchList(string ServiceKey, string BankName, string BranchName) {
            return base.Channel.GetBranchList(ServiceKey, BankName, BranchName);
        }
        
        public System.Threading.Tasks.Task<string> GetBranchListAsync(string ServiceKey, string BankName, string BranchName) {
            return base.Channel.GetBranchListAsync(ServiceKey, BankName, BranchName);
        }
        
        public string ValidateId(string ServiceKey, string IdNumber) {
            return base.Channel.ValidateId(ServiceKey, IdNumber);
        }
        
        public System.Threading.Tasks.Task<string> ValidateIdAsync(string ServiceKey, string IdNumber) {
            return base.Channel.ValidateIdAsync(ServiceKey, IdNumber);
        }
        
        public string GetBranchListBySuburb(string ServiceKey, string BankName, string SuburbName) {
            return base.Channel.GetBranchListBySuburb(ServiceKey, BankName, SuburbName);
        }
        
        public System.Threading.Tasks.Task<string> GetBranchListBySuburbAsync(string ServiceKey, string BankName, string SuburbName) {
            return base.Channel.GetBranchListBySuburbAsync(ServiceKey, BankName, SuburbName);
        }
    }
}
